console.log(typeof (NaN));
console.log(typeof(100));
console.log(typeof("Water"));
console.log(typeof(73.9));
console.log(typeof(9 != 11));
console.log(typeof("Orang" + "e"));
console.log(typeof("Orange" - "s"));
console.log(typeof("4" + "8"));
console.log(typeof("4" - "8"));
console.log(typeof("name" + 3));
console.log(typeof("name" - 3));
console.log(typeof(82 * "word"));
console.log(typeof(1 + "hello"));
console.log(typeof(1 + true));
console.log(typeof("hello" + true));
console.log(typeof(Infinity));
console.log(typeof( 1 == '1'));
console.log(typeof(1 === '1'));
console.log(typeof(1 === '1'));